### ISSUE TITLE
[2021-04-28]수요일까지 해야할 일

### ISSUE THREAD

**Issue by Ujaa** [sk-lookie-routine/lighthouse#11]
수요일(4/28)까지: 

- [x] 서영님-중복체크 가능하게 관심 키워드 페이지 수정(단 한 개 이상 체크해야 다음 버튼 활성화)

- [x] 이유진-회원가입 페이지 유효성 만들어놓기 + ui수정

- [x] 먼저 끝난 사람 다한거 보고 후 : 학과, 같은 내용의 라벨 중복 체크 수정(1학년 고등학교랑 대학교 같이 눌리는거)

채연
- [x]  로그인 첫화면 그림 자르고 제플린 업로드 -> 설명 제플린에 씀
- [x]  닉네임, 아이디 중복체크 만들고 제플린 업로드

**Comment by cyleeeee** [comment]
**유진님**

일단 회원가입에서 아이디 중복확인하는 버튼

- `아이디 입력 칸만 넓이 줄이기 → 그 칸 옆에 중복확인 버튼 배치`  요런 구조로 갈 것 같아요 (수욜오전까지 업로드 할게요 ^0ㅠ)
- + 비밀번호 일치 여부는 가입하기 버튼을 눌러봐야 아는 거죠??
- 닉넴 중복확인 버튼도 머리 굴려볼게요 음 아이디중복이랑 비슷하게 갈 수도 있음

---

**그리고**

그냥 단순 궁금증인데 제가 아까 어떤 어플에 이메일 회원가입이 있길래 한번 해봤거든요🤔

근데 **이메일 인증**을 하더라구요..? ㅎ (이메일로 인증번호 보내서 입력하게 함) 사실 쓰는 입장에서 번거로움 대잔치긴 한데 .. 없어도 상관 없을런지...얘기해봐야할듯 ㅠㅠ

**Comment by leeseooo** [comment]
웹사이트면 괜찮은데 어플에서는 이메일 인증 보통 안 하지 않나요? 중복 확인만 하면 될 것 같아요

**Comment by cyleeeee** [comment]
![image](https://user-images.githubusercontent.com/82392650/116182966-13700080-a758-11eb-9224-5285930e7c8e.png)

ㅋㅋㅋㅋㅋ 저도 이거 뜰때 좀 불편하더라구요 어쨌든 중복확인만 할게요 ^_<

**Comment by Ujaa** [comment]
https://github.com/sk-lookie-routine/lighthouse/issues/11#issuecomment-826980635

@cyleeeee
채연님!!

아헐 저 이거 코멘트 지금 봤네요 .... !!!!!
`비밀번호 일치 여부는 입력하면서 바로 확인`할 수 있어요
허윽 이거 알람오게 못하나...왜 지금 봤지 ㅎㅎㅋㅋ큐ㅠㅠ

**Comment by cyleeeee** [comment]
@Ujaa 괜차나요~~! 아이디 언급하면 알람 바로 가나요?!ㅋㅋㅋㅋㅋㅋ
