### ISSUE TITLE
[2021-05-02]일요일까지 해야할 일

### ISSUE THREAD

**Issue by Ujaa** [sk-lookie-routine/lighthouse#12]
일요일(5/2)까지:

서영🚗
- [x] 회원가입 관련 firestore 공부 후 정리해서 노션에 업로드
- [x] 유저 기본 정보 세팅 생각해오기
- [ ] +옵션: firestore 유효성 체크하는 방법 또는 필요한 유효성 검사 종류 공부

유진🚗
- [x] 회원가입 관련 firestore 공부 후 정리해서 노션에 업로드
- [ ] 유저 기본 정보 세팅 생각해오기
- [ ] +옵션: firestore 유효성 체크하는 방법 또는 필요한 유효성 검사 종류 공부

채연🚗
- [x]  받은 편지함 디자인
- [x]  편지 주고받는 화면 → 우표 갯수, 보관하기, 멘토멘티 닉넴 등등 고려
- [x]  위 화면에서 멘토 프로필 클릭하면 채팅 연결로 유도할 수 있도록 프로필 화면 디자인
- [x]  제플린 1차최종 업로드

**Comment by cyleeeee** [comment]
안 해온 사람 **`디저트`** 사기

**Comment by Ujaa** [comment]
채연님 디저트 안 사려는 그 열정... 잘봤숩니다..

**Comment by cyleeeee** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ🤓
