### ISSUE TITLE
[2021-05-09] 개발 과제 + 질문

### ISSUE THREAD

**Issue by Ujaa** [sk-lookie-routine/lighthouse#13]
채연님에게 드리는 편지...
1. 이거 이미지 하나로 만들어 주세요!! 
![image](https://user-images.githubusercontent.com/40076944/117574660-29e36800-b119-11eb-8919-870d17001ab6.png)
2. 편지 전송중에는 편지 전송중1 화면과 편지 전송중2화면 중 어떤 화면으로 하는건가요?
3. 여기 페이지에서 더보기 누르면 뭐가 나오나요? 그리고 저 하트편지 아이콘 누르면 프로필 들어가는건가요?
![image](https://user-images.githubusercontent.com/40076944/117574988-d540ec80-b11a-11eb-9d10-c613a3bcbee3.png)
4. 이 프로필 페이지는 어떻게 들어가는 건가요? 그리고 프로필 상단 바에 있는 톱니바퀴 아이콘을 눌렀을 때는 뭐가 뜨는건가요? 더보기와 다른건가요?
![image](https://user-images.githubusercontent.com/40076944/117575006-e4279f00-b11a-11eb-8214-5727d360991a.png)

---
##### 서영(@leeseooo)
- [x] finish_screen에서 유저 정보 저장 
- [x] 페이지 하나 새로 구현한 것 중에 골라서 설명 가능하게끔 공부해오기(주석)
- [ ] 편지쓰기 스크린 UI 구현(컴포넌트 분리해서)
 
##### 유진(@Ujaa)
- [ ] 유저 회원가입 로그인
- [x] 페이지 하나 새로 구현한 것 중에 골라서 설명 가능하게끔 공부해오기(주석)
- [x] 받은 편지함 스크린 UI 구현(컴포넌트 분리해서)
---
1. 하단 네비게이션 바 수정
### 편지쓰기 페이지 관련 컴포넌트
2. 키워드 
![image](https://user-images.githubusercontent.com/40076944/117574593-dbce6480-b118-11eb-90b6-de7d2e6b9ceb.png)
3. 편지 보내는 컨테이너(스크롤 기능 + 글자 카운트)
![image](https://user-images.githubusercontent.com/40076944/117574598-e4bf3600-b118-11eb-96b0-8296c1d734ca.png)
4. 팁
![image](https://user-images.githubusercontent.com/40076944/117574615-fa346000-b118-11eb-813f-95e34d4a51cb.png)
5.  프로세스 바 
![image](https://user-images.githubusercontent.com/40076944/117574735-7464e480-b119-11eb-96a1-21c1b6969d8a.png)
---
기타
6. 탭 구현
![image](https://user-images.githubusercontent.com/40076944/117574773-a7a77380-b119-11eb-9825-35bb771e37dd.png)
7. 편지함 알림 박스
![image](https://user-images.githubusercontent.com/40076944/117574756-96f6fd80-b119-11eb-97d8-beb58d71a5b6.png)

**Comment by cyleeeee** [comment]
**# 답변 드립니다(｡･∀･)ﾉﾞ**

---

## 1. 업로드 했어요. 제플린 접속 후 >styleguide 들어가면 볼 수 있습니닷ㅎㅎ

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a58b75da-1921-455b-841d-35e26f69d3ae/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/a58b75da-1921-455b-841d-35e26f69d3ae/Untitled.png)

## 2. 제플린에 떠있는 스크린 기준으로 편지 전송중1 (전송중) → 편지 전송중3(전송완료) 이런 플로우예요! 혹시 불가능하면 말해줘요~

![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/fc3f3eb2-8376-4dc1-9b9e-46359c546651/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/fc3f3eb2-8376-4dc1-9b9e-46359c546651/Untitled.png)

```
눈송이는 제 선물.
```

## 3. 전에도 말했듯이 신고하기 기능이 들어가지 않을까 싶습니다.. 하트편지 아이콘은 ㅋㅋㅋㅋ 그,, 보관하기 기능인데 ... 혹시 말풍선 더블클릭하면 아이콘 생기면서 보관되는거 가능한가요.....?,,,ㅎㅋ,,,..제가 생각해도 무리한 부탁인것 같아서 머쓱하네요.. (더 연구해 볼게요....)

## 4. 채팅창 화면에서 상단 가운데의 '멘토닉네임' 클릭해야 프로필로 접속돼요.

```
더보기 -> 내가 다른 사람의 프로필 볼때
톱니바퀴 -> 내가 나의 프로필 볼때 (앱 설정이나 프로필 수정 등의 화면으로 넘어갈것 같아요)
```

**Comment by cyleeeee** [comment]
# 답변 드립니다(｡･∀･)ﾉﾞ

---
_`이거 이미지 하나로 만들어 주세요!!`_
## 1. 업로드 했어요. 제플린 접속>styleguide 들어가면 볼 수 있습니닷ㅎㅎ

![image](https://user-images.githubusercontent.com/82392650/117686336-ba8d7700-b1f1-11eb-89e2-6938da8e3852.png)

_`편지 전송중에는 편지 전송중1 화면과 편지 전송중2화면 중 어떤 화면으로 하는건가요?`_
## 2. 제플린에 떠있는 스크린 기준으로 편지 전송중1 (전송중) → 편지 전송중3(전송완료) 이런 플로우예요! 혹시 불가능하면 말해줘요~

![image](https://user-images.githubusercontent.com/82392650/117686273-aba6c480-b1f1-11eb-88a1-5f3414e77216.png)

```
눈송이는 제 선물.
```
_`여기 페이지에서 더보기 누르면 뭐가 나오나요? 그리고 저 하트편지 아이콘 누르면 프로필 들어가는건가요?`_
## 3. 전에도 말했듯이 신고하기 기능이 들어가지 않을까 싶습니다.. 하트편지 아이콘은 ㅋㅋㅋㅋ 그,, 보관하기 기능인데 ... 혹시 말풍선 더블클릭하면 아이콘 생기면서 보관되는거 가능한가요.....?,,,ㅎㅋ,,,..제가 생각해도 무리한 부탁인것 같아서 머쓱하네요.. (더 연구해 볼게요....)

`_이 프로필 페이지는 어떻게 들어가는 건가요? 그리고 프로필 상단 바에 있는 톱니바퀴 아이콘을 눌렀을 때는 뭐가 뜨는건가요? 더보기와 다른건가요?_`
## 4. 채팅창 화면에서 상단 가운데의 '멘토닉네임' 클릭해야 프로필로 접속돼요.

```
더보기 -> 내가 다른 사람의 프로필 볼때
톱니바퀴 -> 내가 나의 프로필 볼때 (앱 설정이나 프로필 수정 등의 화면으로 넘어갈것 같아요)
```

**Comment by leeseooo** [comment]
고생하셨어요~!^v^
