### ISSUE TITLE
[2021-05-12] 채연님께 부탁...!

### ISSUE THREAD

**Issue by Ujaa** [sk-lookie-routine/lighthouse#14]
@cyleeeee 
1. 이 갈매기 하나의 이미지로 해주실 수 있나요?
![image](https://user-images.githubusercontent.com/40076944/117915623-a1cfaf00-b320-11eb-9da6-7dd29b27e15e.png)

**Comment by cyleeeee** [comment]
ㅋㅌㅌㅋㅋㅋㅋㅋ뭐야 쟤 왜저래..ㅠ 해드릴게요

**Comment by Ujaa** [comment]
오 벌써 보시다니!!! 감사합니다
채연님! 그 질문 하나 더있는데 얘 누르면 어디로 가나요?? 
![image](https://user-images.githubusercontent.com/40076944/117916126-7f8a6100-b321-11eb-8370-9187c794e4a8.png)

**Comment by Ujaa** [comment]
갈매기 해체되는거랑 갈매기 표정이랑 너무 잘어울림...ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by cyleeeee** [comment]
일단 제플린에 덮어쓰기 했어요🙄💦
![image](https://user-images.githubusercontent.com/82392650/117916477-34248280-b322-11eb-8211-715eaa962d64.png)

**Comment by cyleeeee** [comment]
모든 뒤로가기 버튼은 저희가 정해놓는게 아니구 유저가 이전 단계에서 보던 화면으로 가요!!

**Comment by leeseooo** [comment]
문 닫습니다
