### ISSUE TITLE
가입 완료 뒤로가기 버튼 질문

### ISSUE THREAD

**Issue by Ujaa** [sk-lookie-routine/lighthouse#8]
채연님!
사용자 정보를 언제 저장해야하나 고민하다가 추가 정보 입력 후 완료 버튼을 눌렀을 때 하려고 생각중인데 가입완료 페이지에 있는 뒤로가기 버튼은 없애는 거 어떤가요? 가입이 완료된 상태라고 생각하면 가입과정으로 돌아갈 이유가 없을 것 같아서요!
한번 생각하고 알려주세요😄

그리고 축하해요! 가입이 완료되었습니다 저 문구는 검정색이죠?
![image](https://user-images.githubusercontent.com/40076944/115388888-65c09700-a217-11eb-8373-a6c685a5d037.png)

**Comment by cyleeeee** [comment]
네네 유진님 말씀대로면 **뒤로가기 버튼을 없애고 X버튼으로 바꾸는** 게 나을 것 같아요! (화면을 짤 때 뒤로가기나 X 버튼 둘중 하나는 넣는 게 일반적) 
이 화면에서는 X 버튼이 '확인'이랑 같은 역할이며, 누르면 홈 화면으로 이동하게 될 예정입니닷😄ㅎ 편하게 답 주세요~ 그러면 저 화면 수정해서 업로드 할게요

**Comment by Ujaa** [comment]
아하 x버튼 좋아요! 만약 x 그 구글 아이콘 사용하실 거면 그 아이콘 이름만 알려주셔도 괜찮아요!! 편하신대로 해주세요 감샤합니다

**Comment by cyleeeee** [comment]
![image](https://user-images.githubusercontent.com/82392650/115517279-f0f66700-a2c1-11eb-982e-7a069a935926.png)
제플린에 수정된거 업로드 했어용 아이콘 이름은 clear(24dp)이고, 자세한건 제플린에 설명 붙여놨어용🤩

**Comment by Ujaa** [comment]
감사합니당
